version: '3'
services:
  frontend:
    image: registry.gitlab.propulsion-home.ch/propulsion/projects/templates/react-redux-template:master
    command: "bash -c 'rm -rf /frontend/build/* && cp -r /frontend_tmp/build/* /frontend/build'"
    volumes:
      - frontend:/frontend/build

volumes:
  frontend:
    external: true


networks:
  default:
    external:
      name: templates-network
