export const GET_ALL_STEP_TAX_CONSEQUENCES = 'GET_ALL_STEP_TAX_CONSEQUENCES'
export const ADD_NEW_TAX_CONSEQUENCE = 'ADD_NEW_TAX_CONSEQUENCE'
export const RESET_STEP_TAX_CONSEQUENCES = 'RESET_STEP_TAX_CONSEQUENCES'
