export const GET_MEMBER = 'GET_MEMBER'
export const RESET_MEMBER = 'RESET_MEMBER'
export const SET_MEMBER_FILTER_PROJECT_ID = 'SET_MEMBER_FILTER_PROJECT_ID'
export const RESET_MEMBER_FILTER_PROJECT_ID = 'RESET_MEMBER_FILTER_PROJECT_ID'

