export const GET_ALL_PROJECT_TASKS = 'GET_ALL_PROJECT_TASKS';
export const RESET_TASKS_FOR_PROJECT = 'RESET_TASKS_FOR_PROJECT';
export const SET_TASK_FILTER_STEP_NUMBER = 'SET_TASK_FILTER_STEP_NUMBER'
export const RESET_TASK_FILTER_STEP_NUMBER = 'RESET_TASK_FILTER_STEP_NUMBER'
