export const INCREMENT_STEP_TO_VIEW = 'INCREMENT_STEP_TO_VIEW';
export const DECREMENT_STEP_TO_VIEW = 'DECREMENT_STEP_TO_VIEW';
export const RESET_STEP_TO_VIEW = 'RESET_STEP_TO_VIEW';
export const SKIP_TO_SPECIFIED_STEP = 'SKIP_TO_SPECIFIED_STEP';
